baseURL = "https://youichiro.work"
languageCode = "ja"
title = "youichiro.work"
theme = "hugo-coder"

[params]
    author = "Youichiro Ogawa"
    info = ""
    description = "Youichiro Ogawa's personal website"
    keywords = "小川耀一朗"
    avatarurl = "images/icon.jpg"
    hidecredits = true
    colorscheme = "light"
    favicon_32 = "/images/favicon-32x32.jpeg"
    favicon_16 = "/images/favicon-16x16.jpeg"
    custom_css = ["css/slider.css"]
    custom_js = ["javascript/slider.js"]

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/youichiro/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/cinnamon_416/"

[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"

[[menu.main]]
    name = "Photos"
    weight = 2
    url = "/photos/"

[[menu.main]]
    name = "Blog"
    weight = 3
    url = "/posts/"
