baseURL = ""
languageCode = "ja"
title = "youichiro.work"
theme = "my-hugo-coder"

[params]
    author = "Youichiro Ogawa"
    info = "hoge"
    description = "Youichiro Ogawa's personal website"
    keywords = "小川耀一朗"
    avatarurl = "images/icon.jpg"
    hidecredits = true
    colorscheme = "light"
    favicon_32 = "/images/favicon-32x32.jpeg"
    favicon_16 = "/images/favicon-16x16.jpeg"
    custom_css = ["css/slider.css"]
    custom_js = ["javascript/slider.js"]

[markup.goldmark.renderer]
  hardWraps = true
  unsafe = true

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/youichiro/"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/cinnamon_416/"

[[params.social]]
    name = "SpeakerDeck"
    icon = "fab fa-speaker-deck fa-2x"
    weight = 3
    url = "https://speakerdeck.com/youichiro"

[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"

[[menu.main]]
    name = "Photos"
    weight = 2
    url = "/photos/"

[[menu.main]]
    name = "Posts"
    weight = 3
    url = "/posts/"

